### ISSUE TITLE
Pkg.add() failed due to unnecessary nbextension installation code for anaconda users

### ISSUE THREAD

**Issue by tk3369** [JuliaGizmos/Interact.jl#221]
I have anaconda and nbwidgetsextension is already installed.

```
$ jupyter nbextension list
Known nbextensions:
  config dir: /opt/projects/anaconda3/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
```

This code does not need to be run:

https://github.com/JuliaGizmos/Interact.jl/blob/ce52c14a0772f46924cf16ef60b0a8ba08ebcfda/deps/build.jl#L7-L24

We may think that it would be harmless to run but it fails with a permission problem since I don't own the jupyter directory:

```
$ jupyter nbextension install --py widgetsnbextension
Installing /opt/projects/anaconda3/lib/python3.6/site-packages/widgetsnbextension/static -> jupyter-js-widgets
Traceback (most recent call last):
  File "/opt/projects/anaconda3/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/opt/projects/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/projects/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/projects/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/opt/projects/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/opt/projects/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/opt/projects/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
  File "/opt/projects/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
    destination=dest, logger=logger
  File "/opt/projects/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 126, in install_nbextension
    ensure_dir_exists(nbext)
  File "/opt/projects/anaconda3/lib/python3.6/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/projects/anaconda3/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/projects/anaconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter'
```

I've commented it out to make it work.  But perhaps it would be better to make it an optional step, or make it smarter by skipping it when it's already installed & enabled.

**Comment by piever** [comment]
Same as #233 : closing as the current version of Interact (on master) no longer requires or tries to install nbwidgetsextension.
