### ISSUE TITLE
Error at Pkg.build("Interact")

### ISSUE THREAD

**Issue by justapoise** [JuliaGizmos/Interact.jl#240]
I have installed Interact to follow along a Reactive tutorial. During installation, there was a warning that IJulia is not installed and that I should Pkg.build Interact after installing IJulia. To install IJulia, I used the jupyter from Manjaro repo. IJulia got installed no problems. But when I proceeded to Pkg.build Interact again, I got this:
`julia> Pkg.build("Interact")
INFO: Building Interact
INFO: Enabling widgetsnbextension
Installing /usr/lib/python3.6/site-packages/widgetsnbextension/static -> jupyter-js-widgets
Traceback (most recent call last):
  File "/usr/bin/jupyter-nbextension", line 11, in <module>
    load_entry_point('notebook==5.3.0', 'console_scripts', 'jupyter-nbextension')()
  File "/usr/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/lib/python3.6/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/usr/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/usr/lib/python3.6/site-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/usr/lib/python3.6/site-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
  File "/usr/lib/python3.6/site-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
    destination=dest, logger=logger
  File "/usr/lib/python3.6/site-packages/notebook/nbextensions.py", line 126, in install_nbextension
    ensure_dir_exists(nbext)
  File "/usr/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter'
WARNING: Could not enable widgetsnbextension.
INFO: widgetsnbextension version found: 3.2.1
INFO: A compatible version of widgetsnbextension was found. All good.`

I am not convinced that it is _All good._ Help me.

**Comment by piever** [comment]
Latest (unreleased) Interact does not depend on widgetsnbextensions so you could use that instead. It'll be released in the next few days, but you can do `Pkg.checkout("Interact")` to use it now
